[project]
name = "bot"
version = "0.0.1"
dependencies = [
    "aiogram==3.22.0",
    "pydantic-settings==2.12.0",
    "uvloop==0.22.1; sys_platform == 'linux' or sys_platform == 'darwin'"
]

[tool.uv]
package = false
